name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GH_TOKEN_FIREBASE2 }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT2 }}
          channelId: live
          projectId: ehliyetcabbarhoca
